spring.application.name=dag-engine
server.port = 8091

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/dag_nexus_db
spring.datasource.username=dag_engine_user
spring.datasource.password=nexus_secure_pass
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Settings
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha